#!/bin/bash
#./runs/par-bro-iter.sh
#./runs/par-nobro-iter.sh
#./runs/seq-bro-iter.sh
#./runs/seq-nobro-iter.sh
./runs/src2-tgt1/par-bro-iter.sh
./runs/src2-tgt1/par-nobro-iter.sh
./runs/src2-tgt1/seq-bro-iter.sh
./runs/src2-tgt1/seq-nobro-iter.sh
